### ISSUE TITLE
Issue with all plugins!

### ISSUE THREAD

**Issue by InstaVirus** [kangarko/Puncher#1]
I have bought 3 plugins: Puncher, Confiscate, ChatControl

(I am using PaperSpigot 1.7!) (Host: Shockbyte) I really need a help!

ChatControl --> All natural deaths messages are fine just the slain ones not working!

Confiscate --> Confiscate 1.7.2 encountered a com2! Please check your error.log and report this issue with the information in that file.
09.12 08:29:57 [Server] INFO java.lang.reflect.InvocationTargetException
09.12 08:29:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09.12 08:29:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09.12 08:29:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09.12 08:29:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:98)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ŕł(SourceFile:75)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9$1.ă(SourceFile:30)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.LPt6.ă(SourceFile:124)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:129)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.lPT2.á(SourceFile:35)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:56)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COm4.onEnable(SourceFile:138)
09.12 08:29:57 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
09.12 08:29:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
09.12 08:29:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
09.12 08:29:57 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
09.12 08:29:57 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
09.12 08:29:57 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354)
09.12 08:29:57 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328)
09.12 08:29:57 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284)
09.12 08:29:57 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227)
09.12 08:29:57 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
09.12 08:29:57 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
09.12 08:29:57 [Server] INFO me.kangarko.confiscate. .nul.com2: Report / Value 'mail send InstaVirus [{date}] Confiscate has taken a {material} (reason {log_type}) from {player} at {location}' is already in the list!
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.Lpt3.ă(SourceFile:30)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.coM4.á(SourceFile:86)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.coM4.á(SourceFile:76)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.coM4.ă(SourceFile:52)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.coM4.<init>(SourceFile:37)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.lPT2$protected.init(SourceFile:244)
09.12 08:29:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09.12 08:29:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09.12 08:29:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09.12 08:29:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:98)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ŕł(SourceFile:75)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9$1.ă(SourceFile:30)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.LPt6.ă(SourceFile:124)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:129)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.lPT2.á(SourceFile:35)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:56)
09.12 08:29:57 [Server] INFO at me.kangarko.confiscate. .nul.COm4.onEnable(SourceFile:138)

Puncher --> INFO ___  _  _ _  _ ____ _  _ ____ ____ 
09.12 08:29:57 [Server] INFO |__] |  | |\ | |    |__| |___ |__/ 
09.12 08:29:57 [Server] INFO |    |__| | \| |___ |  | |___ |  \ 
09.12 08:29:57 [Server] INFO -----------------------------------------------------
09.12 08:29:57 [Server] WARN Exception in thread "Thread-17" 
09.12 08:29:57 [Server] WARN java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .aB.new(SourceFile:134)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .COm5.try(SourceFile:31)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .LpT8.try(SourceFile:83)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bW.try(SourceFile:26)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bW.super(SourceFile:21)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bV$1.run(SourceFile:19)
09.12 08:29:57 [Server] WARN Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonSyntaxException
09.12 08:29:57 [Server] WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
09.12 08:29:57 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
09.12 08:29:57 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
09.12 08:29:57 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
09.12 08:29:57 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
09.12 08:29:57 [Server] WARN ... 6 more
09.12 08:29:57 [Server] WARN Exception in thread "Thread-19" 
09.12 08:29:57 [Server] WARN java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .aB.new(SourceFile:134)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .COm5.try(SourceFile:31)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .LpT8.try(SourceFile:83)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bW.try(SourceFile:26)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bW.super(SourceFile:21)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bV$1.run(SourceFile:19)
09.12 08:29:57 [Server] WARN Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonSyntaxException
09.12 08:29:57 [Server] WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
09.12 08:29:57 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
09.12 08:29:57 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
09.12 08:29:57 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
09.12 08:29:57 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
09.12 08:29:57 [Server] WARN ... 6 more
09.12 08:29:57 [Server] WARN Exception in thread "Thread-18" 
09.12 08:29:57 [Server] WARN java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .aB.new(SourceFile:134)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .COm5.try(SourceFile:31)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .LpT8.try(SourceFile:83)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bW.try(SourceFile:26)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bW.super(SourceFile:21)
09.12 08:29:57 [Server] WARN at me.kangarko.puncher.nul . .bV$1.run(SourceFile:19)

**Comment by InstaVirus** [comment]
Please, don't tell me they are not working for 1.7 because I bought them based on your testings... On spigot says Tested Minecraft Vertsions 1.7!

**Comment by InstaVirus** [comment]
I could also pay you more for fixing the code for 1.7! I really need those plugins!

**Comment by kangarko** [comment]
Hello,

### 1. ChatControl Issue
Please post me your messages.yml (use www.pastebin.com) and point out the specific line where it doesn't work.

### 2 Confiscate Issue
The error says that  _Value 'mail send InstaVirus [{date}] Confiscate has taken a {material} (reason {log_type}) from {player} at {location}' is already in the list!_ Please post me your settings.yml, it seems there is some duplicated command.

### 3. Puncher Issue
Please install BungeeChatAPI alongside with Puncher for 1.7.10. I will patch some other bugs that I found during testing in the next release.

**Comment by InstaVirus** [comment]
2017-12-09 16:30 GMT+02:00 kangarko <notifications@github.com>:

**Comment by InstaVirus** [comment]
https://pastebin.com/pMGAAerr

2017-12-09 17:26 GMT+02:00 Fan Kam <fankam02@gmail.com>:

**Comment by InstaVirus** [comment]
Chatcontrol msgs https://pastebin.com/8K3JRjrB

2017-12-09 17:26 GMT+02:00 Fan Kam <fankam02@gmail.com>:

**Comment by kangarko** [comment]
In Confiscate settings, remove line 274 because it is identical to line 275. This will fix it.

What messages are not working in ChatControl, specifically?

**Comment by InstaVirus** [comment]
The slain ones... All natural messages are fine!

2017-12-09 17:33 GMT+02:00 kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
I don't understand. Can you show me the exact message that is not working?

**Comment by InstaVirus** [comment]
2017-12-10 9:16 GMT+02:00 kangarko <notifications@github.com>:

**Comment by InstaVirus** [comment]
Killer: PLAYER
        #
        # Message for the killer, if available:
        #
        Killer_Message:
          - '&cYou just murdered &e{player}!'

        Message:
          - '&e{player} &cwas annoyed to death by &a{killer}&c!'
          - '&a{killer} &chas slain &e{player}&c!'
          - '&a{killer} &cis victorious over &e{player}&c!'
          - '&a{killer} &chas overpowered &e{player} &cin combat!'
          - '&a{killer} &ckilled &e{player}&c!'
          - '&a{killer} &chas ended poor &e{player}&c!'
          - '&a{killer} &covercame &e{player} &cin battle!'
          - '&a{killer} &cdefeated &e{player} &cin mighty struggle!'
          - '&a{killer} &cended all dreams for &e{player}&c!'


2017-12-10 10:14 GMT+02:00 Fan Kam <fankam02@gmail.com>:

**Comment by kangarko** [comment]
It works flawlessly for me, 

![a](https://i.imgur.com/sgXPqfY.png)

How exactly it is not working?

**Comment by InstaVirus** [comment]
Oh, so something is bad with my other plugins! Okay then! The puncher one
left. Only set points not working!

2017-12-10 10:57 GMT+02:00 kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
Sorry I don't understand, what do you mean by 'set points'? I assume you're talking about warning sets from ChatControl right? You can post me your settings from that plugin.

**Comment by InstaVirus** [comment]
When I press the air to get the team's name, then the item does not do
anything!

2017-12-11 21:25 GMT+02:00 kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
Hey, sorry for the delay. I just tested and identified the issue. This will be fixed today. 

Thank you for your patience.

**Comment by InstaVirus** [comment]
Thanks a lot!

2017-12-14 13:26 GMT+02:00 kangarko <notifications@github.com>:
