### ISSUE TITLE
Only use vault as your main currency?

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#10]
Hi there, 

I noticed that you added a function to convert your nuggets to vault money which works great. Do you think of adding an option to only use vault as your main currency? I have multiple mini games on my server and find it easier to have the same currency throughout all games.

**Comment by kangarko** [comment]
You mean completely disable Nuggets and use whatever economy you have instead?

**Comment by Owizardo** [comment]
Yes exatcly. It would make it easier in my opnion to have a option to enable or disable the nugget system.

**Comment by kangarko** [comment]
Good, I am taking this as a suggestion.

**Comment by kangarko** [comment]
Had to delay it due to works on ChatControl. This will come later. Thanks for understanding.
