### ISSUE TITLE
Bug - Custom heads not working correctly

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#11]
Just noticed a problem today testing out the new feature of adding custom head. You can add custom heads and everything seems okay until the match starts. 

When the match starts it seems like your whole armor set (Head, Chest, Legs and Feet) get replaced with a dyed colored leather armor set that matches your team color. Is there a way to disable this?

**Comment by kangarko** [comment]
Hello,

no sorry, this is by default. Each team member is given their respective colored team helmet. I can take that as a suggestion.

**Comment by Owizardo** [comment]
Ok thanks for the quick reply. At the moment the new custom heads function is a bit useless if we cant use it. Is there any way around this? Is there a way to disable teams all together and make it a free for all?

**Comment by kangarko** [comment]
No, teams are mandatory. I can add an option not to add team helmet if one is present in the class, to the yml file in the next version(s).

**Comment by Owizardo** [comment]
Ah ok great, can't wait for the update :). Thank you so much by the way for all the efforts on evolving the game. Its much appreciated.

**Comment by kangarko** [comment]
Added. Write the following to your arena yml's to apply:

![a](https://i.imgur.com/wOhLMb9.png)

**Comment by Owizardo** [comment]
Thank you so much! Is there an update coming soon for this or can I already start using since Puncher version 1.1.8?

**Comment by kangarko** [comment]
It will come in the next release :)
