### ISSUE TITLE
Problem with Rocket and HellFire

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/Puncher#14]
Hello Kangarko!

 Sorry for This issue, i have a problem with Puncher, when i play in a map and use Rocket or HellFire it no works, if i use the rocket the ender pearl he going to subtract from my inventory and he doesn't work :c. Same as that the HellFire, if i call him this doesn't arrive to the coordinates, I Don't have see the console but i don't know... Again sorry for this issue

Minecraft Server Version: 1.8.8
Puncher Version: 1.1.8
Type of Server: Spigot

Thanks and Sorry c:

**Comment by BlackGamer000** [comment]
Oh i forgot him sorry, If you need a Video or a LiveTest please respond to my PM on Spigot c: i will give you the Server Ip 

Thanks and Sorry c:

**Comment by kangarko** [comment]
Any errors in the console? Are you using AsyncWorldEdit? Have you taken arena snapshots?

**Comment by BlackGamer000** [comment]
for Error i don't have see, 

worldEdit i sue FastAsyncWorldEdit because is good for avoid lag

**Comment by BlackGamer000** [comment]
Ok so, sorry for the late Response,

https://nofile.io/f/vXyz0sHhnS9/latest.log

https://nofile.io/f/NEOfzYQuyc2/2018-03-03-3.log.gz

**Comment by BlackGamer000** [comment]
Update: New log on PM on SpigotMC. This 2 Logs are not Exactly :c

**Comment by kangarko** [comment]
FAWE cancels our damage:

> [FAWE `tick-limiter`] Detected and cancelled physics  lag source at (...)

Disable tick-limiter in FAWE.
