### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mjmalec** [kangarko/Puncher#17]
Hello,

I’ve had a few questions regarding Puncher. 
First of all, Puncher has been lagging my server a ton with 8GB of RAM allocated. I’ve left the settings at default values and even went as a far as changing my map completely so there is only one layer to “explode”. Still lagging out my server completely for 3-5 seconds after any of the items are used, rendering the server at that time, unusable and instable. I’ve also found a bug which makes the game not run as it’s suppose to. When all the other teams lose or run out of all of their lives, they can still respawn into the arena, and “spectate” meaning, they aren’t getting hurt, and the last player is still in the arena for the remainder of the arena play time. I’ve also found that players can jump out of the arena, but there isn’t instant void death. It’s the old, slow, annoying one. I’ve also found that creeper eggs don’t work nor do swords. Bows on the other hand do work. Maybe you’re able to provide me with a list of allowed/working items in the games?

I appreciate your help and look forward to hear from you.

Best,
MJ

**Comment by mjmalec** [comment]
Well, my network runs on FAWE, but regardless, lots of lag. I will provide
a /timings report once I arrive home as well as the "Kill_Height"

Thank you!

**Comment by kangarko** [comment]
Closing due to no answer, please comment below if you still have the issue.
