### ISSUE TITLE
Unhandled menu call

### ISSUE THREAD

**Issue by v3Monsta** [kangarko/Puncher#2]
I've come across an issue that prevents me from doing anything with the Arena's GUI. This wasn't a problem when I first installed the plugin. I'd try and figure out the issue myself, but the stack trace is obfuscated.

**Exception:** https://pastebin.com/FJcT4f68

**Environment:** 
- Java: 1.8.0_151
- Paper: git-Paper-1297 (MC: 1.12.2)
- Puncher: 1.1.0
- GameAPI: 1.1.1

**Steps to Reproduce:** 
- Type in /p menu
- Click on "Arenas"

**Comment by kangarko** [comment]
Thanks, fixed.
