### ISSUE TITLE
Arena problems..

### ISSUE THREAD

**Issue by iiTiffers** [kangarko/Puncher#22]
I keep getting this in the console when someone tries to play.

22.06 12:57:20 [Server] INFO *-----------------------------------------------*
22.06 12:57:20 [Server] INFO Snapshot of arena Puncher took too long to restore!
22.06 12:57:20 [Server] INFO Was restoring to stage: initial
22.06 12:57:20 [Server] INFO Took over: 10 seconds
22.06 12:57:20 [Server] INFO Check your WorldEdit update.
22.06 12:57:20 [Server] INFO We have stopped the arena for safety
22.06 12:57:20 [Server] INFO *-----------------------------------------------*

**Comment by kangarko** [comment]
How big is your arena? 
What is your MC version?

I recommend installing FastAsyncWorldEdit to prevent this from happening.

**Comment by iiTiffers** [comment]
I have that. Every time we try to start a game it says it tool longer then
10 second's. I sent a screenshot.

**Comment by kangarko** [comment]
How big is your arena?

**Comment by kangarko** [comment]
Closing due to no answer. Install FastAsyncWorldEdit if it happens again.
