### ISSUE TITLE
Compatible with a survival world?

### ISSUE THREAD

**Issue by farisjaclyn** [kangarko/Puncher#26]
Hey Kangarko,

This may be a silly question - is this mini-game compatible with a survival world?

I'm looking for another way to add fun and excitement to my Minecraft survival world. I've read the wiki and plugin page a few times. I don't see any information on if I can add this to a survival world. I imagine I could, but I just want to be safe. 

I'm not running a multiverse (the one I'm familiar with isn't updating any longer). I understand I'll need worldedit, but I've noticed the new 1.13 beta worldedit has had a lot of issues.

Let me know if you have the answers. Love your plugins. I own two. :)

I'm running the latest version of paper spigot.

Faris

**Comment by kangarko** [comment]
Hey,

yes, you can install Puncher onto your existing survival world. Players' inventories are saved and will be restored after the play.

PS: WorldEdit builds from http://builds.enginehub.org/job/worldedit/last-successful?branch=master are safe and recommended to use on 1.13.2.
