### ISSUE TITLE
Is it possible to add permanent affects on class select?

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#4]
Hi there,

I had an idea to re-create a Super Smash Melee arena using this plugin. Just wondering if it possible to add a permanent affect on select class?

For example, lets say the player selects the Sonic class, I want him to have higher speed until end of game. If the player selects Bowser I want him him to have lower speed and have higher Strength until end of game.

If its not currently possible. Do you think this could be added? Not sure if there would be an easy way to code this so that on game start I could be allowed to run a command for example:

` /effect <player name> <PUNCHER CLASS> <effect ID> <duration> <power>  `

Update:
Meantime I found an temporary solution that compliments this plugin or even the CoreArena:
https://www.spigotmc.org/resources/mmoitems-25-stats-30-abilities-item-edition-gui.39267/ 
Maybe you can see about getting greater compatibility with this plugin.

**Comment by kangarko** [comment]
Hello,

thank you for your suggestion! This is already possible via your class yml file in classes/. Here is an example of giving the SPEED effect:

Tiers:
  #
  # In this case, we are setting specific option for the Tier II.
  #
  2:
    #
    # Which potions shall the player obtain at the arena start?
    # For potion names, ses https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
    #
    # Format: <potion name> <level>: <duration>
    #
    Potions:
      SPEED 2: 1 hour
