### ISSUE TITLE
Super Smash Brawl experience

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#5]
Hi there, 

When purchasing your plugin I had in mind to re-create a Super Smash Bros. Melee type of experience. Using a plugin like [MMOITEM](https://www.spigotmc.org/resources/mmoitems-25-stats-30-abilities-item-edition-gui.39267/). It allows me to create something very similar except for a few things I wished we could improve. 

List 
- Be able to set number lives a player can have. 
- Seperate health system that accumulates damage received. 
- Dynamic Knockback, the more damage a player absorbs, higher vulnerability to knockbacks. 
- Ability to double jump while in mid air
- Ability to create random weapon spawns around the map

That's all I can think of from the top of my head but I think other would be very interested to see this. From what I can see at the moment no other plugins have these features but alot of poeple are seeking these features.

**Comment by kangarko** [comment]
Thanks! You can set the number of lives already in your arena's yml file. I am leaving this open for the future.
