### ISSUE TITLE
Need support for custom heads in the helmet slot

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#6]
Hi there,

Theres a plugin named [MMOTIEM](https://www.spigotmc.org/resources/mmoitems-25-stats-30-abilities-item-edition-gui.39267/) that allows you to create custom armor and also allows custom head skin via the SKULL_ITEM material. I can then add permanent potion effects to a custom head and such ... Together with your plugins, this greatly enchances the game experience. 

At the moment custom armor is allowed if I put in in the class iventory but wont let me set it as a helmet. I also tried setting a regular head under helmet and it wont let me. 

Do you think you could add a bit more flexibility to this? This would allow to make classes in a whole new perpective in my opnion.

**Comment by kangarko** [comment]
Hello,

I have added the ability to insert skull items to the helmet slot in the next release.
