### ISSUE TITLE
Support for Lib's disguise

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Puncher#7]
Hi there, 

Curios to know if you over thought of adding support for the Lib's disguise? This could be handy to further customize classes visually. For example user selects a class and their skin changes according to what was selected (ie Zombie, witch, enderman or even blocks etc ..). 

Heres the link: https://www.spigotmc.org/resources/libs-disguises.32453/

**Comment by kangarko** [comment]
Hello,

I have reviewed that plugin but I don't plan on to adding this feature at the moment, but I am leaving this open as an idea for the future.

**Comment by kangarko** [comment]
Had to close due to works on other priorities.
